import Footer from "@/components/app/footer";
import Header from "@/components/app/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Infinie Maths",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="relative grid size-full min-h-screen grid-rows-[auto_1fr_auto] bg-gray-900">
      <Header />

      <main className="flex flex-col items-center px-4 pt-8 md:px-8">
        <div className="w-full max-w-7xl">{children}</div>
      </main>

      <Footer />
    </div>
  );
}
